[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  CI = "false"
  VITE_BASE_URL = "https://chileaovivo2.netlify.app"
  VITE_SUPABASE_URL = "https://yfgqpaxajeatchcqrehe.supabase.co"
  VITE_SUPABASE_ANON_KEY = "tu-clave-anon-supabase"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
