[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_BASE_URL = "https://chileaovivo.netlify.app"
  VITE_SUPABASE_URL = "https://yfgqpaxajeatchcqrehe.supabase.co"
  VITE_SUPABASE_ANON_KEY = "tu-clave-anon-supabase"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[dev]
  framework = "vite"
  targetPort = 5173
  publish = "dist"
  command = "npm run dev"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_SUPABASE_URL = "https://your-supabase-url.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_SUPABASE_URL = "https://your-supabase-url.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[context.branch-deploy.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_SUPABASE_URL = "https://your-supabase-url.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"
